version: '3'
services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"

  click-api:
    depends_on:
      - db
    build:
      context: apps/click-api
      dockerfile: docker/dev/Dockerfile
    ports:
      - "4000:4000"
    command:
      - docker-tools/runner.rb
      - |
        - wait_for_port: db:5432
        - run: mix phx.server

  click-client:
    depends_on:
      - click-api
    build:
      context: apps/click-client
      dockerfile: docker/dev/Dockerfile
    ports:
      - "4100:4100"
    command:
      - docker-tools/runner.rb
      - |
        - wait_for_port: click-api:4000
        - run: mix phx.server
