version: '3'
services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
  click-api:
    build:
      context: ../..
      dockerfile: priv/docker/Dockerfile.test
    command: ["./priv/docker/start.test.sh"]
    env_file:
      - test.env
    depends_on:
      - db
