version: 2
jobs:
  click_api:
    docker:
      - image: circleci/ruby:2.4.1
      - image: postgres:9.6
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose --file apps/click-api/docker-compose.yml up --build --abort-on-container-exit
  click_client:
    docker:
      - image: circleci/ruby:2.4.1
      - image: postgres:9.6
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose --file apps/click-client/docker-compose.yml up --build --abort-on-container-exit
  integration:
    docker:
      - image: circleci/ruby:2.4.1
      - image: postgres:9.6
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose --file tests/integration/docker-compose.yml up --build --abort-on-container-exit

workflows:
  version: 2
  all:
    jobs:
      - click_api
      - click_client
      - integration:
          requires:
            - click_api
            - click_client
