version: 2

jobs:
  click-api:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Prepare cache checksum
          command: git ls-files -s apps/click-api > .circle.run.checksum && cat .circle.run.checksum
      - restore_cache:
         keys:
           - click-api-{{ checksum ".circle.run.checksum" }}-run-v1
      - run:
          name: Run unit tests
          command: if [ ! -f .circle.run ]; then docker-compose --file apps/click-api/docker-compose.yml up --build --abort-on-container-exit && touch .circle.run; fi
      - save_cache:
          key: click-api-{{ checksum ".circle.run.checksum" }}-run-v1
          paths:
            - .circle.run

  click-client:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Prepare cache checksum
          command: git ls-files -s apps/click-client > .circle.run.checksum && cat .circle.run.checksum
      - restore_cache:
         keys:
           - click-client-{{ checksum ".circle.run.checksum" }}-run-v1
      - run:
          name: Run unit tests
          command: if [ ! -f .circle.run ]; then docker-compose --file apps/click-client/docker-compose.yml up --build --abort-on-container-exit && touch .circle.run; fi
      - save_cache:
          key: click-client-{{ checksum ".circle.run.checksum" }}-run-v1
          paths:
            - .circle.run

  chrome:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Run integration tests
          command: |
            docker-compose --file tests/integration/docker-compose.yml build test-chrome
            docker-compose --file tests/integration/docker-compose.yml run --name app test-chrome ./start.sh
      - run:
          name: Copy test output
          when: always
          command: |
            docker cp app:/usr/src/app/test/reports /tmp
            docker cp app:/usr/src/app/screenshots /tmp
      - store_artifacts:
          path: /tmp/screenshots
      - store_test_results:
          path: /tmp/reports

  firefox:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Run integration tests
          command: docker-compose --file tests/integration/docker-compose.yml up --build --abort-on-container-exit test-firefox

workflows:
  version: 2

  unit:
    jobs:
      - click-api
      - click-client

  integration:
    jobs:
      - approve:
          type: approval
      - chrome:
          requires:
            - approve
      - firefox:
          requires:
            - approve

