version: '3'
services:
  click-client:
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    command:
      - docker-tools/runner.rb
      - |
        - all:
          - run: mix test
          - run: mix credo
